### ISSUE TITLE
没有egl_renderer

### ISSUE THREAD

**Issue by peppa114** [THU-DA-6D-Pose-Group/SO-Pose#1]
我运行 
![1635835335(1)](https://user-images.githubusercontent.com/83171253/139799220-8e9c4fe6-b537-48b1-acc3-8ae9f49134a6.png)
这个代码时发现缺少
![1635835316(1)](https://user-images.githubusercontent.com/83171253/139799225-6ebaa8ad-479a-4bb1-9c60-0c764ae70dcd.png)

请问您可以提供一下嘛？谢谢！

**Comment by wangg12** [comment]
https://github.com/THU-DA-6D-Pose-Group/self6dpp/tree/main/lib/egl_renderer
